user-message: "WARNING: This stack project is generated."

ghc-options:
  "$locals": -fhide-source-paths
  clash-ghc: +RTS -qn4 -A128M -RTS -j4
  clash-prelude: +RTS -qn4 -A128M -RTS -j4
  clash-lib: +RTS -qn4 -A128M -RTS -j4
  recursion-schemes: -O0
  regex-tdfa: -O2

flags:
  clash-lib:
    debug: true
  clash-testsuite:
    cosim: true

allow-newer: true
allow-newer-deps:
  - brick
  - rewrite-inspector
  - tasty-hedgehog

resolver: lts-21.22

# We have 13 packages.
packages:
  - ./benchmark
  - ./benchmark/profiling/prepare
  - ./benchmark/profiling/run
  - ./clash-cores
  - ./clash-cosim
  - ./clash-ffi
  - ./clash-ghc
  - ./clash-lib
  - ./clash-lib-hedgehog
  - ./clash-prelude
  - ./clash-prelude-hedgehog
  - ./clash-term
  - ./tests

extra-deps:
  # Package versions for published packages either not on Stackage or
  # not matching the version on Stackage for the resolver we use.
  # These package-version extra dependencies are equivalent to cabal constraints.
  - brick-0.50
  - concurrent-supply-0.1.8
  - derive-storable-plugin-0.2.3.7
  - prettyprinter-interp-0.2.0.0
  - rewrite-inspector-0.1.0.11
  - tasty-1.5
